### ISSUE TITLE
Cannot install on PHP 8.0.12

### ISSUE THREAD

**Issue by lewisstancer** [laminas-api-tools/api-tools-skeleton#44]
#### Summary

Cannot install via Composer on PHP version 8.0.12

#### Current behavior

Problem 1
    - laminas-api-tools/api-tools-admin is locked to version 1.10.0 and an update of this package was not requested.
    - laminas-api-tools/api-tools-admin 1.10.0 requires php ^7.3 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 2
    - laminas/laminas-console is locked to version 2.8.0 and an update of this package was not requested.
    - laminas/laminas-console 2.8.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 3
    - laminas/laminas-developer-tools is locked to version 1.3.2 and an update of this package was not requested.
    - laminas/laminas-developer-tools 1.3.2 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 4
    - zfcampus/zf-console is locked to version 1.4.0 and an update of this package was not requested.
    - zfcampus/zf-console 1.4.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 5
    - zfcampus/zf-deploy is locked to version 1.3.0 and an update of this package was not requested.
    - zfcampus/zf-deploy 1.3.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
  Problem 6
    - laminas/laminas-console 2.8.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
    - laminas/laminas-test 3.5.1 requires laminas/laminas-console ^2.6 -> satisfiable by laminas/laminas-console[2.8.0].
    - laminas/laminas-test is locked to version 3.5.1 and an update of this package was not requested.

#### How to reproduce

Tried the composer create-project command and also tried cloning the git and running composer install

#### Expected behavior

Install successfully

**Comment by JohnyProkie** [comment]
Try to run with `--ignore-platform-reqs` flag, see https://github.com/laminas-api-tools/api-tools-skeleton/issues/26

However it produced error in my already existing module. See following log:
```
api-tools-skeleton-apigility-1  | [Tue Dec 07 17:05:05.055016 2021] [php:error] [pid 19] [client 172.21.0.1:52164]
PHP Fatal error:
Uncaught Laminas\\ModuleManager\\Exception\\RuntimeException: Module (StatusLib) could not be initialized.
in /var/www/vendor/laminas/laminas-modulemanager/src/ModuleManager.php:183
Stack trace:
#0 /var/www/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(155): Laminas\\ModuleManager\\ModuleManager->loadModuleByName()
#1 /var/www/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(77): Laminas\\ModuleManager\\ModuleManager->loadModule()
#2 /var/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\\ModuleManager\\ModuleManager->onLoadModules()
#3 /var/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\\EventManager\\EventManager->triggerListeners()
#4 /var/www/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(100): Laminas\\EventManager\\EventManager->triggerEvent()
#5 /var/www/vendor/laminas/laminas-mvc/src/Application.php(257): Laminas\\ModuleManager\\ModuleManager->loadModules()
#6 /var/www/public/index.php(60): Laminas\\Mvc\\Application::init()
#7 {main}
  thrown in /var/www/vendor/laminas/laminas-modulemanager/src/ModuleManager.php on line 183, referer: http://localhost:8080/

```

**Comment by Ocramius** [comment]
Since this is a skeleton, we may perhaps want to remove the lockfile, although unsure :thinking:
